version: '2'
services:
  pigx-mysql:
    build:
      context: ./
      dockerfile: ./doc/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: pigx-mysql
    image: pigx-mysql
    ports:
      - 3306:3306

  pigx-zookeeper:
    image: zookeeper:3.4.13
    ports:
      - 2181:2181
    restart: always

  pigx-redis:
    image: redis:4.0.10
    ports:
      - 6379:6379
    restart: always

  pigx-eureka:
    build:
      context: ./
      dockerfile: ./pigx-eureka/Dockerfile
    restart: always
    container_name: pigx-eureka
    image: pigx-eureka
    ports:
      - 8761:8761

  pigx-config:
    build:
      context: ./
      dockerfile: ./pigx-config/Dockerfile
    restart: always
    container_name: pigx-config
    image: pigx-config

  pigx-gateway:
    build:
      context: ./
      dockerfile: ./pigx-gateway/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    container_name: pigx-gateway
    image: pigx-gateway
    ports:
      - 9999:9999

  pigx-auth:
    build:
      context: ./
      dockerfile: ./pigx-auth/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    container_name: pigx-auth
    image: pigx-auth

  pigx-upms:
    build:
      context: ./
      dockerfile: ./pigx-upms/pigx-upms-biz/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    container_name: pigx-upms
    image: pigx-upms

  pigx-monitor:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-monitor/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    image: pigx-monitor
    container_name: pigx-monitor
    ports:
      - 5001:5001

  pigx-daemon:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-daemon/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    image: pigx-daemon
    container_name: pigx-daemon
    ports:
      - 5002:5002

  pigx-codegen:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-codegen/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    image: pigx-codegen
    container_name: pigx-codegen


  pigx-activiti:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-activiti/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    image: pigx-activiti
    container_name: pigx-activiti

  pigx-tx-manager:
    build:
      context: ./
      dockerfile: ./pigx-visual/pigx-tx-manager/Dockerfile
    depends_on:
      - pigx-config
    restart: always
    image: pigx-tx-manager
    container_name: pigx-tx-manager
    ports:
      - 5004:5004
      - 9998:9998
