## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      client-secret: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      scope: server
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /*/portal

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://pigx-mysql:3306/coffeewx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    hikari:
      connection-init-sql: SET NAMES utf8mb4
  resources:
    static-locations: classpath:/static/,classpath:/views/


# 租户表维护
pigx:
  tenant:
    column: tenant_id
    tables:
      - t_wx_account
      - t_wx_account_fans