# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql:3306/pigx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# 社交登录配置新
social:
  wx:
    appid: wxd1678d3f83b1d83a
    secret: 6ddb043f94da5d2172926abe8533504f
